(()=>{
'use strict';
const C=window.IMNOTFINE_CONFIG||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const K={p:'inf.v2.posts',c:'inf.v2.circles',u:'inf.v2.profile',r:'inf.v2.reactions'},CATS=['사소한 재난','일','돈','관계','몸','외로움'],PH=['오늘도 계획대로 망함','웃기지만 안 웃김','이럴 줄은 몰랐지','그냥 봐줘','조언은 괜찮아'],RISK=/(자살|죽고\s*싶|자해|손목|유서|살해|죽여|폭행|강간|피투성이)/i;
const S={mode:'demo',db:null,user:null,profile:null,circles:[],circle:null,posts:[],reactions:{},image:null,category:CATS[0],story:null,install:null,blocked:new Set(JSON.parse(localStorage.getItem('inf.blocked')||'[]'))};
document.addEventListener('DOMContentLoaded',init);
async function init(){bind();seed();await backend();await load();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error);launch();network();addEventListener('online',network);addEventListener('offline',network)}
function bind(){document.body.addEventListener('click',e=>act(e.target.closest('[data-action],[data-tab],[data-circle],[data-react]')));$('#cameraInput').onchange=$('#galleryInput').onchange=file;$('#captionInput').oninput=()=>{$('#charCount').textContent=$('#captionInput').value.length+'/80';safety()};$('#formSubmit').onclick=()=>window.__submit?.();addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.install=e;$('[data-action=install]').hidden=false})}
function act(b){if(!b)return;if(b.dataset.tab)return tab(b.dataset.tab);if(b.dataset.circle)return choose(b.dataset.circle);if(b.dataset.react)return react(b.dataset.post,b.dataset.react);const a=b.dataset.action,m={home:()=>tab('feed'),camera:()=>pick(1),gallery:()=>pick(0),profile:()=>tab('profile'),install,invite,auth:authForm,'open-circle':()=>open('#circleModal'),'close-circle':()=>close('#circleModal'),'close-compose':closeCompose,'close-story':()=>close('#storyModal'),'close-form':()=>close('#formModal'),'close-menu':()=>close('#menuModal'),publish,'create-circle':createCircle,'join-circle':joinCircle,'reset-demo':reset,archive,blocked,privacy};if(m[a])return m[a]();if(a==='story')story(b.dataset.post);if(a==='share-story')shareStory();if(a==='save-story')saveStory();if(a==='share-post')sharePost(b.dataset.post);if(a==='post-menu')menu(b.dataset.post)}
async function backend(){if(!C.SUPABASE_URL||!C.SUPABASE_ANON_KEY||C.DEMO_MODE||!window.supabase)return;try{S.db=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);S.user=(await S.db.auth.getSession()).data.session?.user||null;S.mode='live';S.db.auth.onAuthStateChange(async(_,x)=>{S.user=x?.user||null;await load();render()})}catch(e){console.error(e);toast('서버 연결 실패: 데모 모드로 시작합니다.')}}
function seed(){if(!localStorage.getItem(K.u))localStorage.setItem(K.u,JSON.stringify({id:'demo-me',display_name:'라이언',email:'demo@imnotfine.local'}));if(!localStorage.getItem(K.c))localStorage.setItem(K.c,JSON.stringify([{id:'c1',name:'자영업자 재난본부',invite_code:'NOTFIN',members:4},{id:'c2',name:'오늘도 출근한 사람들',invite_code:'WORKED',members:7}]));if(!localStorage.getItem(K.p))localStorage.setItem(K.p,JSON.stringify([{id:'p1',user_id:'u1',author:'매튜',circle_id:'c1',category:'사소한 재난',caption:'회의 3분 전. 노트북은 무사합니다. 아마도.',image_url:demo('coffee'),created_at:new Date(Date.now()-1260000).toISOString(),expires_at:new Date(Date.now()+604800000).toISOString(),visibility:'circle'},{id:'p2',user_id:'u2',author:'데이빗',circle_id:'c1',category:'일',caption:'저장 버튼을 누르기 직전 브라우저가 모든 것을 잊었습니다.',image_url:demo('error'),created_at:new Date(Date.now()-10800000).toISOString(),expires_at:new Date(Date.now()+604800000).toISOString(),visibility:'circle'}]))}
async function load(){if(S.mode==='demo'){S.profile=JSON.parse(localStorage.getItem(K.u));S.user={id:S.profile.id,email:S.profile.email};S.circles=JSON.parse(localStorage.getItem(K.c)||'[]');S.circle=S.circles.find(x=>x.id===localStorage.getItem('inf.activeCircle'))||S.circles[0]||null;S.posts=JSON.parse(localStorage.getItem(K.p)||'[]').filter(x=>new Date(x.expires_at)>new Date());S.reactions=JSON.parse(localStorage.getItem(K.r)||'{}');return}if(!S.user){S.profile=null;S.circles=[];S.posts=[];return}const uid=S.user.id,[p,m]=await Promise.all([S.db.from('profiles').select('*').eq('id',uid).maybeSingle(),S.db.from('circle_members').select('circle_id,circles(*)').eq('user_id',uid)]);S.profile=p.data||{id:uid,display_name:S.user.email?.split('@')[0]||'사용자'};S.circles=(m.data||[]).map(x=>x.circles).filter(Boolean);S.circle=S.circles.find(x=>x.id===localStorage.getItem('inf.activeCircle'))||S.circles[0]||null;await loadPosts()}
async function loadPosts(){if(S.mode!=='live')return;let q=S.db.from('posts').select('*,profiles(display_name),reactions(user_id,reaction_type)').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(30);if(S.circle)q=q.eq('circle_id',S.circle.id);const {data,error}=await q;if(error)return console.error(error);S.posts=(data||[]).map(x=>({...x,author:x.profiles?.display_name||'익명'}));S.reactions={};S.posts.forEach(x=>(x.reactions||[]).forEach(r=>{if(r.user_id===S.user.id)S.reactions[x.id]=r.reaction_type}))}
function render(){profile();circles();feed();$('#modeBadge').textContent=S.mode==='live'?'LIVE':'DEMO';$('#modeBadge').classList.toggle('live',S.mode==='live')}
function profile(){const p=S.profile||{display_name:'방문자'},i=(p.display_name||'나')[0];$('#avatarText').textContent=$('#profileAvatar').textContent=i;$('#profileName').textContent=p.display_name||'방문자';$('#profileEmail').textContent=S.mode==='live'?(S.user?.email||'로그인 필요'):'데모 모드 · 이 기기에만 저장';$('#authButton').textContent=S.mode==='live'&&S.user?'로그아웃':'로그인하고 친구와 연결';$('#archiveCount').textContent=S.posts.filter(x=>x.user_id===S.user?.id).length}
function circles(){const h=S.circles.map(x=>`<button class="circle-card ${S.circle?.id===x.id?'active':''}" data-circle="${E(x.id)}"><span class="circle-avatar">${E(x.name[0])}</span><div><b>${E(x.name)}</b><small>${x.members||'?'}명 · 초대 코드 ${E(x.invite_code||'------')}</small></div><span>${S.circle?.id===x.id?'✓':'›'}</span></button>`).join('');$('#circleList').innerHTML=h||'<div class="empty"><h3>서클이 없습니다.</h3></div>';$('#circlePicker').innerHTML=h;$('#circleName').textContent=S.circle?.name||'서클 선택';$('#circleInitial').textContent=S.circle?.name?.[0]||'?'}
function feed(){const a=S.posts.filter(x=>!S.blocked.has(x.user_id)&&(x.visibility==='public'||x.visibility==='private'&&x.user_id===S.user?.id||!S.circle||x.circle_id===S.circle.id));$('#feed').innerHTML=a.map(card).join('');$('#emptyFeed').hidden=!!a.length}
function card(x){const mine=x.user_id===S.user?.id;return`<article class="post"><header class="post-head"><div class="author"><span class="circle-avatar">${E((x.author||'?')[0])}</span><span><b>${E(x.author||'익명')}</b><br><small>${ago(x.created_at)}</small></span></div><div><span class="tag">${E(x.category)}</span><button class="more-btn" data-action="post-menu" data-post="${x.id}">•••</button></div></header><img class="post-photo" src="${A(x.image_url)}"><div class="post-body"><p class="caption">${E(x.caption)}</p><div class="meta"><span>${x.visibility==='private'?'나만 보기':x.visibility==='public'?'익명 공감 피드':E(S.circles.find(c=>c.id===x.circle_id)?.name||'서클')}</span><span>${left(x.expires_at)}일 후 삭제</span></div><div class="reaction-row">${['봤어','나도 그래','버텼네'].map(r=>`<button class="${S.reactions[x.id]===r?'on':''}" data-react="${r}" data-post="${x.id}">${r}</button>`).join('')}</div><div class="tool-row"><button data-action="story" data-post="${x.id}">스토리 티저</button><button data-action="share-post" data-post="${x.id}">친구에게 보내기</button>${mine?`<button data-action="post-menu" data-post="${x.id}">관리</button>`:''}</div></div></article>`}
function tab(x){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+x+'View')?.classList.add('active');$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===x));$('#hero').hidden=x!=='feed';scrollTo({top:0,behavior:'smooth'})}
async function choose(id){S.circle=S.circles.find(x=>x.id===id)||S.circle;localStorage.setItem('inf.activeCircle',id);close('#circleModal');if(S.mode==='live')await loadPosts();render()}
function pick(cam){$(cam?'#cameraInput':'#galleryInput').click()}async function file(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;S.image=await compress(f);$('#imagePreview').innerHTML=`<img src="${S.image}">`;compose()}
function compose(){S.category=CATS[0];$('#categoryChips').innerHTML=CATS.map((x,i)=>`<button class="${i?'':'on'}" data-cat="${E(x)}">${E(x)}</button>`).join('');$('#phraseChips').innerHTML=PH.map(x=>`<button data-phrase="${E(x)}">${E(x)}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{$$('[data-cat]').forEach(x=>x.classList.remove('on'));b.classList.add('on');S.category=b.dataset.cat});$$('[data-phrase]').forEach(b=>b.onclick=()=>{$('#captionInput').value=b.dataset.phrase;$('#captionInput').dispatchEvent(new Event('input'))});open('#composeModal')}
function closeCompose(){close('#composeModal');S.image=null;$('#captionInput').value='';$('#charCount').textContent='0/80';$('#imagePreview').innerHTML='<span>사진을 선택하세요</span>';$('#safetyWarning').hidden=true}
function safety(){const r=RISK.test($('#captionInput').value);$('#safetyWarning').hidden=!r;$('#safetyWarning').textContent=r?'심각한 위험 신호가 포함될 수 있습니다. 공개 게시보다 신뢰하는 사람이나 지역의 긴급 지원에 직접 연락하는 것을 우선하세요.':'';return r}
async function publish(){const cap=$('#captionInput').value.trim(),vis=$('#visibilityInput').value;if(!S.image)return toast('사진을 먼저 선택하세요.');if(!cap)return toast('한마디를 입력하세요.');if(safety())return toast('위험 표현이 감지되어 공개 게시를 중단했습니다.');if(vis==='circle'&&!S.circle)return toast('서클을 먼저 선택하세요.');busy(1);try{if(S.mode==='demo'){S.posts.unshift({id:crypto.randomUUID(),user_id:S.user.id,author:S.profile.display_name,circle_id:S.circle?.id||null,category:S.category,caption:cap,image_url:S.image,created_at:new Date().toISOString(),expires_at:new Date(Date.now()+604800000).toISOString(),visibility:vis});localStorage.setItem(K.p,JSON.stringify(S.posts))}else{const blob=await(await fetch(S.image)).blob(),path=S.user.id+'/'+crypto.randomUUID()+'.jpg',bucket=C.STORAGE_BUCKET||'post-images',up=await S.db.storage.from(bucket).upload(path,blob,{contentType:'image/jpeg'});if(up.error)throw up.error;const url=S.db.storage.from(bucket).getPublicUrl(path).data.publicUrl,ins=await S.db.from('posts').insert({user_id:S.user.id,circle_id:vis==='circle'?S.circle.id:null,category:S.category,caption:cap,image_url:url,storage_path:path,visibility:vis,expires_at:new Date(Date.now()+604800000).toISOString()});if(ins.error)throw ins.error;await loadPosts()}closeCompose();render();toast('오늘의 한 장을 올렸습니다.');setTimeout(()=>story(S.posts[0].id),200)}catch(e){console.error(e);toast('게시하지 못했습니다. 설정을 확인하세요.')}finally{busy(0)}}
async function react(id,type){if(S.mode==='demo'){S.reactions[id]=S.reactions[id]===type?'':type;localStorage.setItem(K.r,JSON.stringify(S.reactions));return feed()}if(!S.user)return authForm();if(S.reactions[id]===type){await S.db.from('reactions').delete().eq('post_id',id).eq('user_id',S.user.id);delete S.reactions[id]}else{await S.db.from('reactions').upsert({post_id:id,user_id:S.user.id,reaction_type:type},{onConflict:'post_id,user_id'});S.reactions[id]=type}feed()}
function menu(id){const x=S.posts.find(p=>p.id===id),mine=x.user_id===S.user?.id;$('#menuBody').innerHTML=(mine?'<button class="danger" data-menu="delete">게시물 삭제</button>':'')+'<button data-menu="report">신고하기</button>'+(!mine?'<button data-menu="block">이 사용자 차단</button>':'');$$('[data-menu]').forEach(b=>b.onclick=async()=>{if(b.dataset.menu==='delete')await remove(x);if(b.dataset.menu==='report')await report(x);if(b.dataset.menu==='block'){S.blocked.add(x.user_id);localStorage.setItem('inf.blocked',JSON.stringify([...S.blocked]));feed();toast('사용자를 차단했습니다.')}close('#menuModal')});open('#menuModal')}
async function remove(x){if(S.mode==='demo'){S.posts=S.posts.filter(p=>p.id!==x.id);localStorage.setItem(K.p,JSON.stringify(S.posts))}else{await S.db.from('posts').delete().eq('id',x.id);if(x.storage_path)await S.db.storage.from(C.STORAGE_BUCKET||'post-images').remove([x.storage_path]);await loadPosts()}feed();toast('삭제했습니다.')}
async function report(x){if(S.mode==='live')await S.db.from('reports').insert({reporter_id:S.user.id,post_id:x.id,reason:'user_report'});S.posts=S.posts.filter(p=>p.id!==x.id);feed();toast('신고 접수 후 게시물을 숨겼습니다.')}
async function story(id){const x=S.posts.find(p=>p.id===id);if(!x)return;S.story=x;const i=await image(x.image_url),c=$('#storyCanvas').getContext('2d'),w=1080,h=1920;c.fillStyle='#171717';c.fillRect(0,0,w,h);c.save();c.filter='blur(30px) brightness(.52)';cover(c,i,-70,-70,w+140,h+140);c.restore();c.fillStyle='#f1bc3f';c.beginPath();c.arc(125,125,53,0,Math.PI*2);c.fill();c.fillStyle='#171717';c.textAlign='center';c.font='900 45px Arial';c.fillText(':(',125,143);c.textAlign='left';c.fillStyle='white';c.font='900 39px Arial';c.fillText("I'M NOT FINE",205,120);c.font='900 76px Arial';c.fillText('오늘 약간 망했습니다.',74,1445);c.font='700 43px Arial';wrap(c,x.caption,74,1550,920,59);c.fillStyle='#f1bc3f';c.fillRect(74,1760,932,96);c.fillStyle='#171717';c.font='900 31px Arial';c.textAlign='center';c.fillText('실제 사진은 암낫파인에서 보기 →',540,1821);open('#storyModal')}
async function shareStory(){const b=await blob(),f=new File([b],'imnotfine-story.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[f]}))try{return await navigator.share({files:[f],text:'오늘 약간 망했습니다. 사진은 암낫파인에만 있습니다.'})}catch{}down(b,'imnotfine-story.png')}async function saveStory(){down(await blob(),'imnotfine-story.png')}
async function sharePost(id){const x=S.posts.find(p=>p.id===id),url=(C.APP_BASE_URL||location.href)+'?post='+encodeURIComponent(id),text=`오늘 약간 망했습니다. “${x.caption}”`;if(navigator.share)try{return await navigator.share({title:"I'm Not Fine",text,url})}catch{}await navigator.clipboard?.writeText(text+'\n'+url);toast('공유 링크를 복사했습니다.')}
function invite(){if(!S.circle)return toast('서클을 선택하세요.');const url=(C.APP_BASE_URL||location.href)+'?join='+S.circle.invite_code,text=`'${S.circle.name}' 암낫파인 서클 초대 · 코드 ${S.circle.invite_code}`;navigator.share?navigator.share({title:'암낫파인 서클 초대',text,url}).catch(()=>{}):navigator.clipboard?.writeText(text+'\n'+url).then(()=>toast('초대 링크를 복사했습니다.'))}
function createCircle(){form('NEW CIRCLE','새 서클 만들기',[['name','서클 이름','자영업자 재난본부']],async v=>{if(!v.name.trim())return;const code=Math.random().toString(36).slice(2,8).toUpperCase();if(S.mode==='demo'){const c={id:crypto.randomUUID(),name:v.name.trim(),invite_code:code,members:1};S.circles.push(c);S.circle=c;localStorage.setItem(K.c,JSON.stringify(S.circles))}else{const r=await S.db.from('circles').insert({name:v.name.trim(),owner_id:S.user.id,invite_code:code}).select().single();if(r.error)throw r.error;await S.db.from('circle_members').insert({circle_id:r.data.id,user_id:S.user.id,role:'owner'});await load()}close('#formModal');render();toast('서클을 만들었습니다.')})}
function joinCircle(pre=''){form('JOIN CIRCLE','초대 코드로 참여',[['code','6자리 초대 코드','NOTFIN',pre]],async v=>{const code=v.code.trim().toUpperCase();if(S.mode==='demo'){let c=S.circles.find(x=>x.invite_code===code);if(!c){c={id:crypto.randomUUID(),name:'초대받은 서클 '+code,invite_code:code,members:2};S.circles.push(c);localStorage.setItem(K.c,JSON.stringify(S.circles))}S.circle=c}else{const r=await S.db.from('circles').select('*').eq('invite_code',code).single();if(r.error)throw r.error;await S.db.from('circle_members').insert({circle_id:r.data.id,user_id:S.user.id,role:'member'});await load();S.circle=S.circles.find(x=>x.id===r.data.id)}close('#formModal');render();toast('서클에 참여했습니다.')})}
function authForm(){if(S.mode==='live'&&S.user)return S.db.auth.signOut();form('SIGN IN',S.mode==='demo'?'데모 프로필 설정':'이메일로 로그인',S.mode==='demo'?[['name','표시 이름','라이언',S.profile?.display_name||'']]:[['email','이메일','you@example.com']],async v=>{if(S.mode==='demo'){S.profile={id:'demo-me',display_name:v.name.trim()||'사용자',email:'demo@imnotfine.local'};S.user={id:S.profile.id};localStorage.setItem(K.u,JSON.stringify(S.profile));render();toast('프로필을 저장했습니다.')}else{const r=await S.db.auth.signInWithOtp({email:v.email,options:{emailRedirectTo:location.href}});if(r.error)throw r.error;toast('로그인 링크를 이메일로 보냈습니다.')}close('#formModal')})}
function form(eye,title,fields,submit){$('#formEyebrow').textContent=eye;$('#formTitle').textContent=title;$('#formBody').innerHTML=fields.map(f=>`<div class="form-group"><label>${E(f[1])}</label><input class="form-input" id="form-${f[0]}" placeholder="${A(f[2]||'')}" value="${A(f[3]||'')}"></div>`).join('');window.__submit=async()=>{const v={};fields.forEach(f=>v[f[0]]=$('#form-'+f[0]).value);try{await submit(v)}catch(e){console.error(e);toast('처리하지 못했습니다.')}};open('#formModal')}
function archive(){const a=S.posts.filter(x=>x.user_id===S.user?.id);$('#menuBody').innerHTML=a.length?a.map(x=>`<button>${E(x.category)} · ${E(x.caption.slice(0,35))}</button>`).join(''):'<p class="form-help">보관된 게시물이 없습니다.</p>';open('#menuModal')}function blocked(){$('#menuBody').innerHTML=S.blocked.size?'<p class="form-help">차단한 사용자가 '+S.blocked.size+'명 있습니다.</p><button id="unblock">모두 해제</button>':'<p class="form-help">차단한 사용자가 없습니다.</p>';$('#unblock')?.addEventListener('click',()=>{S.blocked.clear();localStorage.removeItem('inf.blocked');close('#menuModal');feed()});open('#menuModal')}function privacy(){$('#menuBody').innerHTML='<p class="form-help">팔로워 수와 공개 반응 수를 표시하지 않습니다.<br><br>게시물은 7일 후 만료되며 신고된 게시물은 숨김 처리됩니다.</p>';open('#menuModal')}
function reset(){if(S.mode!=='demo')return;Object.values(K).forEach(localStorage.removeItem.bind(localStorage));localStorage.removeItem('inf.activeCircle');location.reload()}async function install(){if(!S.install)return toast('브라우저 메뉴에서 홈 화면에 추가하세요.');S.install.prompt();await S.install.userChoice;S.install=null}
async function launch(){const q=new URLSearchParams(location.search);if(q.get('camera'))setTimeout(()=>pick(1),250);if(q.get('invite'))setTimeout(invite,250);if(q.get('join'))setTimeout(()=>joinCircle(q.get('join')),250);if(q.get('shared')){const x=await shared();if(x?.file){S.image=await data(x.file);$('#imagePreview').innerHTML=`<img src="${S.image}">`;$('#captionInput').value=x.text||'';compose()}}}
function open(s){$(s).classList.add('open');document.body.style.overflow='hidden'}function close(s){$(s).classList.remove('open');document.body.style.overflow=''}function busy(x){$('[data-action=publish]').disabled=x;$('[data-action=publish]').textContent=x?'올리는 중…':'오늘의 한 장 올리기'}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('on'),2300)}function network(){$('#offlineBar').hidden=navigator.onLine}
function ago(d){const s=(Date.now()-new Date(d))/1000;return s<60?'방금':s<3600?Math.floor(s/60)+'분 전':s<86400?Math.floor(s/3600)+'시간 전':Math.floor(s/86400)+'일 전'}function left(d){return Math.max(0,Math.ceil((new Date(d)-Date.now())/86400000))}function E(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}const A=E;
function compress(f){return new Promise((r,j)=>{const q=new FileReader;q.onload=()=>{const i=new Image;i.onload=()=>{const s=Math.min(1,1500/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=i.width*s;c.height=i.height*s;c.getContext('2d').drawImage(i,0,0,c.width,c.height);r(c.toDataURL('image/jpeg',.82))};i.onerror=j;i.src=q.result};q.onerror=j;q.readAsDataURL(f)})}function data(f){return new Promise((r,j)=>{const q=new FileReader;q.onload=()=>r(q.result);q.onerror=j;q.readAsDataURL(f)})}function image(src){return new Promise((r,j)=>{const i=new Image;i.crossOrigin='anonymous';i.onload=()=>r(i);i.onerror=j;i.src=src})}function cover(c,i,x,y,w,h){const s=Math.max(w/i.width,h/i.height),sw=w/s,sh=h/s;c.drawImage(i,(i.width-sw)/2,(i.height-sh)/2,sw,sh,x,y,w,h)}function wrap(c,t,x,y,m,l){let z='';for(const ch of t){const q=z+ch;if(c.measureText(q).width>m){c.fillText(z,x,y);z=ch;y+=l}else z=q}c.fillText(z,x,y)}function blob(){return new Promise(r=>$('#storyCanvas').toBlob(r,'image/png'))}function down(b,n){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click()}
function shared(){return new Promise((r,j)=>{const q=indexedDB.open('imnotfine-share',1);q.onupgradeneeded=()=>q.result.createObjectStore('inbox');q.onerror=()=>j(q.error);q.onsuccess=()=>{const t=q.result.transaction('inbox','readwrite'),s=t.objectStore('inbox'),g=s.get('latest');g.onsuccess=()=>{const v=g.result;s.delete('latest');r(v)}}})}
function demo(k){return'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(k==='coffee'?`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"><rect width="800" height="600" fill="#d7c8ad"/><rect y="365" width="800" height="235" fill="#b58d62"/><rect x="215" y="115" width="370" height="260" rx="18" fill="#252525"/><rect x="235" y="135" width="330" height="205" fill="#d8e2dd"/><path d="M195 395C280 350 420 430 510 382C585 342 650 378 700 430V560H150Z" fill="#6f3d22"/><text x="48" y="74" font-family="Arial" font-size="34" font-weight="700">MEETING IN 03:00</text></svg>`:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"><rect width="800" height="600" fill="#cad3d8"/><rect x="90" y="75" width="620" height="410" rx="20" fill="#25292d"/><rect x="120" y="115" width="560" height="310" fill="#edf0ea"/><circle cx="400" cy="235" r="58" fill="#bd493d"/><path d="M375 210l50 50m0-50l-50 50" stroke="white" stroke-width="16"/><text x="180" y="540" font-family="Arial" font-size="39" font-weight="700">UNSAVED CHANGES</text></svg>`)}
})();
